@hostname = localhost
@port = 8181
@host = {{hostname}}:{{port}}
@contentType = application/json
@accessToken = 
###
GET http://{{host}}/install
Content-Type: {{contentType}}

### New Role
POST http://{{host}}/role
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "name": "Administrator",
    "description" : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
}

### Get All Roles
GET http://{{host}}/roles?page=1&limit=10
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### Get All Roles
GET http://{{host}}/roles?focus=trash
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### Delete Roles
DELETE http://{{host}}/roles
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
   "role_id":[
      1,
      3
   ]
}

### Delete Roles
DELETE http://{{host}}/roles?focus=trash
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
   "role_id":[
      1
   ]
}