@hostname = localhost
@port = 8181
@host = {{hostname}}:{{port}}
@contentType = application/json
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImIwMmZkY2MyLWI2NjktNDg1My04ZWEyLWYzMjViZDEzOGNhMCIsImNvbnRleHQiOnsiZW1haWwiOiJhb2ZpZWVAYW9maWVlLmRldiIsImRpc3BsYXlfbmFtZSI6IiIsInJvbGUiOiJBZG1pbmlzdHJhdG9yIn0sImV4cCI6MTYzMDMyNDcxNCwiaWF0IjoxNjMwMzIzODE0LCJpc3MiOiJEaWFibG9zIiwic3ViIjoiNzA0YjE2OGYtYWJkNS00MjMwLTlmZTItZWY4OWEzNDQ5NzU5In0.pMlnlHAzYIYhLzCMk4uc7GdoYEm5uuPS_OBTObBGg7E

###
GET http://{{host}}/install
Content-Type: {{contentType}}

### New Role
POST http://{{host}}/role
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "name": "Customer",
    "description" : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
}

### Get Role
GET http://{{host}}/role/2
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### Update Role
PUT http://{{host}}/role/4
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "name": "Artist Manager3",
    "description" : "ส่วนบริหารจัดการศิลปิน"
}
### Get All Roles
GET http://{{host}}/roles?page=1&limit=10&sort=asc&softing=name
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### Get All Roles
GET http://{{host}}/roles?focus=trash
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### Delete Roles
DELETE http://{{host}}/roles
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
   "role_id":[
      6
   ]
}

### Delete Roles from trash
DELETE http://{{host}}/roles?focus=trash
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
   "role_id":[
      4
   ]
}

### Restore Roles from trash
PUT http://{{host}}/roles/restore
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
   "role_id":[
      4
   ]
}