@hostname = localhost
@port = 8181
@host = {{hostname}}:{{port}}
@contentType = application/json
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImQ4NGEwNmU0LTE1M2EtNGQyZS05NzBhLTkwMDUzODM1ZjBkYyIsImNvbnRleHQiOnsiZW1haWwiOiJhb2ZpZWU2NjZAZ21haWwuY29tIiwiZGlzcGxheV9uYW1lIjoiS2hvbWtyaWQgTGVyZHByYXNlcnQiLCJyb2xlIjoiQWRtaW5pc3RyYXRvciJ9LCJleHAiOjE2Mjc4NzgyMzIsImlhdCI6MTYyNzg3NzMzMiwiaXNzIjoiRGlhYmxvcyIsInN1YiI6ImQ0ZWEyMjFmLTc2MjMtNDAzMC1iYmRlLTQxMDRmMzZjNjBhNCJ9.CiUT1touNym_iGmlAmg_khhmip_OFWCEoYhb9dHuMEY

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjg0ODIxMzIsImlhdCI6MTYyNzg3NzMzMiwiaXNzIjoiRGlhYmxvcyIsInJlZnJlc2hfdXVpZCI6IjM5ZjAwMmJiLWVmM2EtNGE4MC05NDgxLWJjMDY2Y2I3NjFjOCIsInN1YiI6ImQ0ZWEyMjFmLTc2MjMtNDAzMC1iYmRlLTQxMDRmMzZjNjBhNCJ9.GIoWaRC-USCyjTeE_YB-RzMETivF6lkQu2dxjQ6Ad00
###
GET http://{{host}}/
Content-Type: {{contentType}}

###
POST http://{{host}}/auth
Content-Type: {{contentType}}

{
    "email":"aofiee666@gmail.com",
    "password":"password"
}

###
DELETE  http://{{host}}/auth/logout
Authorization: Bearer {{accessToken}}

###
POST http://{{host}}/auth/refresh_token
Content-Type: application/x-www-form-urlencoded

refresh_token={{refreshToken}}

###
POST http://{{host}}/auth/refresh_token
Content-Type: {{contentType}}

{"refresh_token":"{{refreshToken}}"}