@hostname = localhost
@port = 8181
@host = {{hostname}}:{{port}}
@contentType = application/json
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImNhNWUzYzJkLTNiZmEtNGIwNy04YmI2LTlhYmQxYzRlNTNlZSIsImNvbnRleHQiOnsiZW1haWwiOiJhb2ZpZWU2NjZAZ21haWwuY29tIiwiZGlzcGxheV9uYW1lIjoiIiwicm9sZSI6IkFkbWluaXN0cmF0b3IifSwiZXhwIjoxNjI4NTAwNTYwLCJpYXQiOjE2Mjg0OTk2NjAsImlzcyI6IkRpYWJsb3MiLCJzdWIiOiI1ZTJkMjMxZi05MTU2LTQxN2EtYjgwZS1iZjEwYmJjNTcyMTYifQ.F5k28l0SbTGGnu5dxFobwoVw-ZIWTa7nHTPIV2jcSW8
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjkxMDQ0NjAsImlhdCI6MTYyODQ5OTY2MCwiaXNzIjoiRGlhYmxvcyIsInJlZnJlc2hfdXVpZCI6ImMyZmI0MTFlLWIyYWItNDdlZS1hZWZlLTU5NjI4ZmU2YjkxZSIsInN1YiI6IjVlMmQyMzFmLTkxNTYtNDE3YS1iODBlLWJmMTBiYmM1NzIxNiJ9.wrqnJhqhnJOeRGB08kCIOzhOwtnBB7YyS9Wi1sX6_1M
###
GET http://{{host}}/
Content-Type: {{contentType}}

###
POST http://{{host}}/auth
Content-Type: {{contentType}}

{
    "email":"aofiee666@gmail.com",
    "password":"password"
}

###
DELETE  http://{{host}}/auth/logout
Authorization: Bearer {{accessToken}}

###
POST http://{{host}}/auth/refresh_token
Content-Type: application/x-www-form-urlencoded

refresh_token={{refreshToken}}

###
POST http://{{host}}/auth/refresh_token
Content-Type: {{contentType}}

{"refresh_token":"{{refreshToken}}"}