@hostname = localhost
@port = 8181
@host = {{hostname}}:{{port}}
@contentType = application/json
@accessToken = 
@refreshToken = 
###
GET http://{{host}}/
Content-Type: {{contentType}}

###
POST http://{{host}}/auth
Content-Type: {{contentType}}

{
    "email":"khomkrid@twinsynergy.co.th",
    "password":"password"
}

###
DELETE  http://{{host}}/logout
Authorization: Bearer {{refreshToken}}

###
POST http://{{host}}/refresh
Content-Type: application/x-www-form-urlencoded

refresh_token={{refreshToken}}

###
POST http://{{host}}/refresh
Content-Type: {{contentType}}

{"refresh_token":"{{refreshToken}}"}