@hostname = localhost
@port = 8181
@host = {{hostname}}:{{port}}
@contentType = application/json
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjEyMWMyNDhiLWYwMDMtNGUzNy05M2FkLTAwMWYzYjJmNWEwYSIsImNvbnRleHQiOnsiZW1haWwiOiJhb2ZpZWU2NjZAZ21haWwuY29tIiwiZGlzcGxheV9uYW1lIjoiIiwicm9sZSI6IkFkbWluaXN0cmF0b3IifSwiZXhwIjoxNjI4MDY1ODk0LCJpYXQiOjE2MjgwNjQ5OTQsImlzcyI6IkRpYWJsb3MiLCJzdWIiOiJjODQ4YTRmYS01OTIwLTRmZDktODAxOS1mMTg1OTA4OGJhMTkifQ.l8w-pfZYIWT2JuIbetd4j3ssGUdvUzTYNre1oP1cwxU

###
GET http://{{host}}/
Content-Type: {{contentType}}

###Create User
POST http://{{host}}/user
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "email":"weerawith@twinsynergy.co.th",
    "password":"password",
    "name":"Weerawit Phaktawee",
    "telephone":"0925905444",
    "role_id":2
}

###Update User
PUT  http://{{host}}/user/c848a4fa-5920-4fd9-8019-f1859088ba19
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "email":"aofiee666@gmail.com",
    "password":"password",
    "name":"Khomkrid Lerdprasert",
    "telephone":"0925905444",
    "role_id":1
}

###Get my profile
GET http://{{host}}/user/me
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get User Profile by id
GET http://{{host}}/user/25fd623a-3c69-4d38-9004-0a9666f99483
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Delete User to Trash
DELETE http://{{host}}/user/25fd623a-3c69-4d38-9004-0a9666f99483
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get all users default page = 0 , limit = 10, sort = desc , focus = inbox, keyword = all
GET http://{{host}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get all users แบบระบุ page และแบ่งหน้า และ sort
GET http://{{host}}/users?page=0&keyword=all&sort=ASC&field=name&limit=5&page=1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get all users ในถังขยะ offset = (page*limit)+page
GET http://{{host}}/users?focus=trash&keyword=all&page=1&limit=10
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Delete Users from Inbox
DELETE http://{{host}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "users_id":[
        "068d74fa-64ad-4984-b881-ba972d86b2ed"
    ]
}


###Delete Users from trash
DELETE http://{{host}}/users?focus=trash
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "users_id":[
        "068d74fa-64ad-4984-b881-ba972d86b2ed"
    ]
}

###Restore User from trash to inbox
PUT http://{{host}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "users_id":[
        "03571757-daa6-427e-bdad-fa41bc6c67fb",
        "64a15228-636c-4dec-ae05-2baff17bed63",
        "068d74fa-64ad-4984-b881-ba972d86b2ed"
    ]
}

###Show Role Items
GET http://{{host}}/roles
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}                    