@hostname = localhost
@port = 8181
@host = {{hostname}}:{{port}}
@contentType = application/json
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImViNDNhYjA2LTVlMzItNDVlMS05Yzg2LWM0OWQzN2QzMjU5MiIsImNvbnRleHQiOnsiZW1haWwiOiJhb2ZpZWU2NjZAZ21haWwuY29tIiwiZGlzcGxheV9uYW1lIjoiIiwicm9sZSI6IkFkbWluaXN0cmF0b3IifSwiZXhwIjoxNjI4NTA2NjgwLCJpYXQiOjE2Mjg1MDU3ODAsImlzcyI6IkRpYWJsb3MiLCJzdWIiOiI1OGRhMzg2ZC0yMzRlLTRmOTktODg4ZC0xN2FhZGU3OGFhZWYifQ.PGK10w8s7TD4b3uNm6ro7HUlX2Oed80tR39SgK7aIaA

###
GET http://{{host}}/
Content-Type: {{contentType}}

###Create User
POST http://{{host}}/user
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "email":"weerawith@twinsynergy.co.th",
    "password":"password",
    "name":"Weerawit Phaktawee",
    "telephone":"0925905444",
    "role_id":2
}

###Update User
PUT  http://{{host}}/user/37619465-e4af-4c7a-877d-bd8c1b0db2f3
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "email":"weerawith@twinsynergy.co.th",
    "password":"password",
    "name":"Weerawit Phaktawee",
    "telephone":"0925905444",
    "role_id":1
}

###Get my profile
GET http://{{host}}/user/me
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get User Profile by id
GET http://{{host}}/user/393ac8ce-4ce7-4529-a9fb-9dbed6a14fe1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Delete User to Trash
DELETE http://{{host}}/user/393ac8ce-4ce7-4529-a9fb-9dbed6a14fe1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get all users default page = 0 , limit = 10, sort = desc , focus = inbox, keyword = all
GET http://{{host}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get all users แบบระบุ page และแบ่งหน้า และ sort
GET http://{{host}}/users?page=0&keyword=all&sort=ASC&field=name&limit=5&page=1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get all users ในถังขยะ offset = (page*limit)+page
GET http://{{host}}/users?focus=trash&keyword=all&page=1&limit=10
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Delete Users from Inbox
DELETE http://{{host}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "users_id":[
        "37619465-e4af-4c7a-877d-bd8c1b0db2f3"
    ]
}


###Delete Users from trash
DELETE http://{{host}}/users?focus=trash
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "users_id":[
        "37619465-e4af-4c7a-877d-bd8c1b0db2f3"
    ]
}

###Restore User from trash to inbox
PUT http://{{host}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "users_id":[
        "393ac8ce-4ce7-4529-a9fb-9dbed6a14fe1"
    ]
}

###Show Role Items
GET http://{{host}}/roles
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}                    

###
GET http://{{host}}/modules?keyword=all&page=2&limit=3
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}    

###
PUT http://{{host}}/module/21
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "name": "Update Role",
    "description": "แก้ไข Role",
    "method": "PUT",
    "module_slug": "/role"
}