@hostname = localhost
@port = 8181
@host = {{hostname}}:{{port}}
@contentType = application/json
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImFlMzVkODdkLTY1MTYtNGM0Yy1hMmU1LTFlNmExNWQxYjk4YyIsImNvbnRleHQiOnsiZW1haWwiOiJhb2ZpZWU2NjZAZ21haWwuY29tIiwiZGlzcGxheV9uYW1lIjoiS2hvbWtyaWQgTGVyZHByYXNlcnQiLCJyb2xlIjoiQWRtaW5pc3RyYXRvciJ9LCJleHAiOjE2Mjc5Nzc4MTIsImlhdCI6MTYyNzk3NjkxMiwiaXNzIjoiRGlhYmxvcyIsInN1YiI6ImQ0ZWEyMjFmLTc2MjMtNDAzMC1iYmRlLTQxMDRmMzZjNjBhNCJ9.npsjKBZQ0ZJZKRXG5yNNAp1Uc2rhNEh8glwm-h79OCg

###
GET http://{{host}}/
Content-Type: {{contentType}}

###Create User
POST http://{{host}}/user
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "email":"weerawith@twinsynergy.co.th",
    "password":"password",
    "name":"Weerawit Phaktawee",
    "telephone":"0925905444",
    "role_id":2
}

###Update User
PUT  http://{{host}}/user/d4ea221f-7623-4030-bbde-4104f36c60a4
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "email":"aofiee666@gmail.com",
    "password":"password",
    "name":"Khomkrid Lerdprasert",
    "telephone":"0925905444",
    "role_id":1
}

###Get my profile
GET http://{{host}}/user/me
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get User Profile by id
GET http://{{host}}/user/64a15228-636c-4dec-ae05-2baff17bed63
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Delete User to Trash
DELETE http://{{host}}/user/9833ccde-805f-4d11-b7a9-0e8cbfdd69a5
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get all users default page = 0 , limit = 10, sort = desc , focus = inbox, keyword = all
GET http://{{host}}/users?keyword=Khomkrid
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get all users แบบระบุ page และแบ่งหน้า และ sort
GET http://{{host}}/users?page=0&keyword=all&sort=ASC&field=name&limit=5&page=1
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Get all users ในถังขยะ offset = (page*limit)+page
GET http://{{host}}/users?focus=trash&keyword=all&page=1&limit=10
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

###Delete Users from Inbox
DELETE http://{{host}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "users_id":[
        "03571757-daa6-427e-bdad-fa41bc6c67fb",
        "068d74fa-64ad-4984-b881-ba972d86b2ed"
    ]
}


###Delete Users from trash
DELETE http://{{host}}/users?focus=trash
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "users_id":[
        "16a4e078-11b0-48b5-b679-147e6f145f4a"
    ]
}

###Restore User from trash to inbox
PUT http://{{host}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "users_id":[
        "03571757-daa6-427e-bdad-fa41bc6c67fb",
        "64a15228-636c-4dec-ae05-2baff17bed63",
        "068d74fa-64ad-4984-b881-ba972d86b2ed"
    ]
}

###Show Role Items
GET http://{{host}}/roles
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}                    