// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/aofiee/barroth/models"
	mock "github.com/stretchr/testify/mock"
)

// AuthenticationUseCase is an autogenerated mock type for the AuthenticationUseCase type
type AuthenticationUseCase struct {
	mock.Mock
}

// Login provides a mock function with given fields: m, email, password
func (_m *AuthenticationUseCase) Login(m *models.Users, email string, password string) error {
	ret := _m.Called(m, email, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Users, string, string) error); ok {
		r0 = rf(m, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
