// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/aofiee/barroth/models"
	mock "github.com/stretchr/testify/mock"
)

// AuthenticationRepository is an autogenerated mock type for the AuthenticationRepository type
type AuthenticationRepository struct {
	mock.Mock
}

// Login provides a mock function with given fields: m, username, password
func (_m *AuthenticationRepository) Login(m *models.Users, username string, password string) error {
	ret := _m.Called(m, username, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Users, string, string) error); ok {
		r0 = rf(m, username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Logout provides a mock function with given fields:
func (_m *AuthenticationRepository) Logout() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshToken provides a mock function with given fields: ExpireRefreshToken
func (_m *AuthenticationRepository) RefreshToken(ExpireRefreshToken string) (string, error) {
	ret := _m.Called(ExpireRefreshToken)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(ExpireRefreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ExpireRefreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
