// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/aofiee/barroth/models"
	mock "github.com/stretchr/testify/mock"
)

// ModuleRepository is an autogenerated mock type for the ModuleRepository type
type ModuleRepository struct {
	mock.Mock
}

// CreateModule provides a mock function with given fields: m
func (_m *ModuleRepository) CreateModule(m *models.Modules) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Modules) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetModule provides a mock function with given fields: m, id
func (_m *ModuleRepository) GetModule(m *models.Modules, id string) error {
	ret := _m.Called(m, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Modules, string) error); ok {
		r0 = rf(m, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetModuleBySlug provides a mock function with given fields: m, method, slug
func (_m *ModuleRepository) GetModuleBySlug(m *models.Modules, method string, slug string) error {
	ret := _m.Called(m, method, slug)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Modules, string, string) error); ok {
		r0 = rf(m, method, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateModule provides a mock function with given fields: m, id
func (_m *ModuleRepository) UpdateModule(m *models.Modules, id string) error { // Compliant
	ret := _m.Called(m, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Modules, string) error); ok {
		r0 = rf(m, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
