// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/aofiee/barroth/models"
	mock "github.com/stretchr/testify/mock"
)

// ModuleUseCase is an autogenerated mock type for the ModuleUseCase type
type ModuleUseCase struct {
	mock.Mock
}

// CreateModule provides a mock function with given fields: m
func (_m *ModuleUseCase) CreateModule(m *models.Modules) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Modules) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetModule provides a mock function with given fields: m, slug
func (_m *ModuleUseCase) GetModule(m *models.Modules, slug string) error {
	ret := _m.Called(m, slug)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Modules, string) error); ok {
		r0 = rf(m, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateModule provides a mock function with given fields: m, id
func (_m *ModuleUseCase) UpdateModule(m *models.Modules, id string) error {
	ret := _m.Called(m, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Modules, string) error); ok {
		r0 = rf(m, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
