// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/aofiee/barroth/models"
	mock "github.com/stretchr/testify/mock"
)

// PermissionsUseCase is an autogenerated mock type for the PermissionsUseCase type
type PermissionsUseCase struct {
	mock.Mock
}

// SetPermissions provides a mock function with given fields: m
func (_m *PermissionsUseCase) SetPermissions(m *[]models.Permissions) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]models.Permissions) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
