// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/aofiee/barroth/models"
	mock "github.com/stretchr/testify/mock"
)

// RoleRepository is an autogenerated mock type for the RoleRepository type
type RoleRepository struct {
	mock.Mock
}

// CreateRole provides a mock function with given fields: m
func (_m *RoleRepository) CreateRole(m *models.RoleItems) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.RoleItems) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRoles provides a mock function with given fields: focus, id
func (_m *RoleRepository) DeleteRoles(focus string, id []int) (int64, error) {
	ret := _m.Called(focus, id)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, []int) int64); ok {
		r0 = rf(focus, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []int) error); ok {
		r1 = rf(focus, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllRoles provides a mock function with given fields: m, keyword, sorting, sortField, page, limit, focus
func (_m *RoleRepository) GetAllRoles(m *[]models.RoleItems, keyword string, sorting string, sortField string, page string, limit string, focus string) error {
	ret := _m.Called(m, keyword, sorting, sortField, page, limit, focus)

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]models.RoleItems, string, string, string, string, string, string) error); ok {
		r0 = rf(m, keyword, sorting, sortField, page, limit, focus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRole provides a mock function with given fields: m, id
func (_m *RoleRepository) GetRole(m *models.RoleItems, id string) error {
	ret := _m.Called(m, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.RoleItems, string) error); ok {
		r0 = rf(m, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRole provides a mock function with given fields: m, id
func (_m *RoleRepository) UpdateRole(m *models.RoleItems, id string) error {
	ret := _m.Called(m, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.RoleItems, string) error); ok {
		r0 = rf(m, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
