// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/aofiee/barroth/models"
	mock "github.com/stretchr/testify/mock"
)

// UserUseCase is an autogenerated mock type for the UserUseCase type
type UserUseCase struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: m
func (_m *UserUseCase) CreateUser(m *models.Users) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Users) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUsers provides a mock function with given fields: focus, id
func (_m *UserUseCase) DeleteUsers(focus string, id []string) (int64, error) {
	ret := _m.Called(focus, id)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, []string) int64); ok {
		r0 = rf(focus, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(focus, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUsers provides a mock function with given fields: m, keyword, sorting, sortField, page, limit, focus
func (_m *UserUseCase) GetAllUsers(m *[]models.Users, keyword string, sorting string, sortField string, page string, limit string, focus string) (int64, error) {
	ret := _m.Called(m, keyword, sorting, sortField, page, limit, focus)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*[]models.Users, string, string, string, string, string, string) int64); ok {
		r0 = rf(m, keyword, sorting, sortField, page, limit, focus)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*[]models.Users, string, string, string, string, string, string) error); ok {
		r1 = rf(m, keyword, sorting, sortField, page, limit, focus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: m, uuid
func (_m *UserUseCase) GetUser(m *models.Users, uuid string) error {
	ret := _m.Called(m, uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Users, string) error); ok {
		r0 = rf(m, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestoreUsers provides a mock function with given fields: id
func (_m *UserUseCase) RestoreUsers(id []string) (int64, error) {
	ret := _m.Called(id)

	var r0 int64
	if rf, ok := ret.Get(0).(func([]string) int64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: m, id
func (_m *UserUseCase) UpdateUser(m *models.Users, id string) error {
	ret := _m.Called(m, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Users, string) error); ok {
		r0 = rf(m, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
