name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          cd ./services && go mod tidy
      - name: Go Run Test
        run: |
          cd ./services && go test "./..." -coverprofile="coverage.out" -covermode=count -json > report.json
      - name: fix code coverage paths
        working-directory: ./services
        run: |
          sed -i 's/\/home\/runner\/work\/barroth\/barroth\//\/github\/workspace\/services//g' coverage.out
          sed -i 's/\/home\/runner\/work\/barroth\/barroth\//\/github\/workspace\/services//g' report.json
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          